Repository mojohaus/exec-maven-plugin, pull requests merged in 2022-07, with the labels that each got.

#315 Fix build badge for current CI system
  README.md
Labels: maintenance

#316 Testing with Maven 3.2.5 and 3.8.6
  .github/workflows/maven.yml
Labels: build

#317 Cleanup project
  pom.xml
Labels: maintenance

#318 Cleanup project site
  src/site/apt/examples/example-exec-or-java-change-classpath-scope.apt.vm
  src/site/apt/index.apt
  src/site/fml/faq.fml
  src/site/site.xml
Labels: maintenance

#319 Require Maven 3.2.5
  pom.xml
  src/test/java/org/codehaus/mojo/exec/ExecJavaMojoTest.java
  src/test/java/org/codehaus/mojo/exec/ExecMojoTest.java
Labels: enhancement

#77 Fix NullPointerException when using plugin dependencies in version 1.6.0
  src/it/projects/project6/pom.xml
  src/it/projects/project6/project5exec/pom.xml
  src/it/projects/project6/project5lib/pom.xml
  src/it/projects/project6/project5lib/src/main/java/org/codehaus/mojo/exec/project5lib/ExampleLibrary.java
  src/it/projects/project6/project5libB/pom.xml
  src/it/projects/project6/project5libB/src/main/java/org/codehaus/mojo/exec/project5libB/App.java
  src/it/projects/project6/verify.groovy
  src/main/java/org/codehaus/mojo/exec/AbstractExecMojo.java
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
Labels: bug

#321 Get rid of maven-artifact-transfer from dependencies
  pom.xml
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
Labels: maintenance
