Repository mojohaus/exec-maven-plugin, pull requests merged in 2023-11, with the labels that each got.

#392 Workaround for concurrent access to local repository on Windows by ITs
  pom.xml
Labels: build

#390 [#389] Add option 'blockSystemExit' to 'java' mojo
  pom.xml
  src/it/projects/mexec-gh-389-block-exit-non-zero/invoker.properties
  src/it/projects/mexec-gh-389-block-exit-non-zero/pom.xml
  src/it/projects/mexec-gh-389-block-exit-non-zero/src/main/java/Main.java
  src/it/projects/mexec-gh-389-block-exit-non-zero/verify.groovy
  src/it/projects/mexec-gh-389-block-exit-zero/invoker.properties
  src/it/projects/mexec-gh-389-block-exit-zero/pom.xml
  src/it/projects/mexec-gh-389-block-exit-zero/src/main/java/Main.java
  src/it/projects/mexec-gh-389-block-exit-zero/verify.groovy
  src/it/projects/mexec-gh-389-default-permit-exit/invoker.properties
  src/it/projects/mexec-gh-389-default-permit-exit/pom.xml
  src/it/projects/mexec-gh-389-default-permit-exit/src/main/java/Main.java
  src/it/projects/mexec-gh-389-default-permit-exit/verify.groovy
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
  src/main/java/org/codehaus/mojo/exec/SystemExitException.java
  src/main/java/org/codehaus/mojo/exec/SystemExitManager.java
Labels: enhancement

#157 Only prefix program output with thread name when running with multiple threads
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
Labels: enhancement

#394 Remove unused killAfter options
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
  src/test/java/org/codehaus/mojo/exec/ExecJavaMojoTest.java
Labels: enhancement

#395 Enable spotless for code formatting
  pom.xml
  src/main/java/org/codehaus/mojo/exec/AbstractExecMojo.java
  src/main/java/org/codehaus/mojo/exec/AbstractPath.java
  src/main/java/org/codehaus/mojo/exec/AbstractProperty.java
  src/main/java/org/codehaus/mojo/exec/Classpath.java
  src/main/java/org/codehaus/mojo/exec/EnvStreamConsumer.java
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
  src/main/java/org/codehaus/mojo/exec/ExecutableDependency.java
  src/main/java/org/codehaus/mojo/exec/ExtendedExecutor.java
  src/main/java/org/codehaus/mojo/exec/LineRedirectOutputStream.java
  src/main/java/org/codehaus/mojo/exec/Modulepath.java
  src/main/java/org/codehaus/mojo/exec/PathsToolchain.java
  src/main/java/org/codehaus/mojo/exec/PathsToolchainFactory.java
  src/main/java/org/codehaus/mojo/exec/ProjectProperties.java
  src/main/java/org/codehaus/mojo/exec/Property.java
  src/main/java/org/codehaus/mojo/exec/SystemExitException.java
  src/main/java/org/codehaus/mojo/exec/SystemExitManager.java
  src/main/java/org/codehaus/mojo/exec/SystemProperty.java
  src/main/java/org/codehaus/mojo/exec/URLClassLoaderBuilder.java
  src/test/java/org/codehaus/mojo/exec/DummyMain.java
  src/test/java/org/codehaus/mojo/exec/ExecJavaMojoTest.java
  src/test/java/org/codehaus/mojo/exec/ExecMojoTest.java
  src/test/java/org/codehaus/mojo/exec/FindClassInClasspath.java
  src/test/java/org/codehaus/mojo/exec/HelloSystemProperty.java
  src/test/java/org/codehaus/mojo/exec/LineRedirectOutputStreamTest.java
  src/test/java/org/codehaus/mojo/exec/MainUncooperative.java
  src/test/java/org/codehaus/mojo/exec/MainWithThreads.java
  src/test/java/org/codehaus/mojo/exec/NoMain.java
  src/test/java/org/codehaus/mojo/exec/Slf4jMain.java
  src/test/java/org/codehaus/mojo/exec/ThrowingMain.java
  src/test/java/org/codehaus/mojo/exec/URLClassLoaderBuilderTest.java
  src/test/java/org/codehaus/plexus/util/interpolation/Interpolator.java
  src/test/java/org/codehaus/plexus/util/interpolation/RegexBasedInterpolator.java
  src/test/java/org/codehaus/plexus/util/interpolation/ValueSource.java
Labels: maintenance

#396 Code cleanups - use newer JDK features
  .gitignore
  pom.xml
  src/main/java/org/codehaus/mojo/exec/AbstractPath.java
  src/main/java/org/codehaus/mojo/exec/EnvStreamConsumer.java
  src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
  src/main/java/org/codehaus/mojo/exec/PathsToolchainFactory.java
  src/test/java/org/codehaus/mojo/exec/ExecMojoTest.java
  src/test/java/org/codehaus/plexus/util/interpolation/Interpolator.java
  src/test/java/org/codehaus/plexus/util/interpolation/RegexBasedInterpolator.java
  src/test/java/org/codehaus/plexus/util/interpolation/ValueSource.java
Labels: maintenance
