Repository mojohaus/exec-maven-plugin, pull requests merged in 2024-08, with the labels that each got.

#427 Do not get UPPERCASE env vars
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
Labels: bug

#437 Remove Log4j 1.2.x from ITs
  src/it/projects/git-issue-60-exec/pom.xml
  src/it/projects/git-issue-60-exec/verify.groovy
  src/it/projects/git-issue-60-java/pom.xml
  src/it/projects/git-issue-60-java/verify.groovy
  src/it/projects/setup-parent/invoker.properties
  src/it/projects/setup-parent/pom.xml
Labels: maintenance

#440 Remove redundant spotless configuration
  pom.xml
Labels: maintenance

#439 fix: NPE because declared MavenSession field hides field of superclass
  README.md
  src/it/projects/mexec-439/invoker.properties
  src/it/projects/mexec-439/pom.xml
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
Labels: bug

#444 Use shared release drafter GH Action
  .github/workflows/release-drafter.yml
Labels: build

#443 Use Maven4 enabled with GH Action
  .github/workflows/maven.yml
Labels: build
