Repository mojohaus/exec-maven-plugin, pull requests merged in 2025-09, with the labels that each got.

#487 [ExecMojo]Add `getShebang` method to correctly set the command line executable name
  src/it/projects/envscript/src/build/env.sh
  src/main/java/org/codehaus/mojo/exec/ExecMojo.java
  src/test/java/org/codehaus/mojo/exec/ExecMojoTest.java
Labels: enhancement

#491 Re-run failed tests
  pom.xml
Labels: maintenance

#492 Use Maven 3.9.11 in dependencies, still requires 3.6.3 as minimum
  pom.xml
Labels: dependencies

#488 fix inheritIo option
  src/main/java/org/codehaus/mojo/exec/ExtendedExecutor.java
Labels: bug
